### ISSUE TITLE
Compile error reporting based on kernel 5.10

### ISSUE THREAD

**Issue by small-leek** [kunpengcompute/KAEdriver#7]
There are some changes after kernel 5.10, which need to be adapted：
1.type VM_ fault_ T changes from int to unsigned int;

2.remove return value of debugfs_create_regset32();

3.pci_cleanup_aer_uncorrect_error_status()-->pci_aer_clear_nonfatal_status()

**Comment by yuhongxiao123456** [comment]
kae is not support kernel 5.10, the requirement is being planned.
